name: github-ci.yml
on:
  push:
    tags:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.PROOF_PACKAGE_CI_TOKEN }}

jobs:
  deploy:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout CI scripts
        uses: actions/checkout@v4
        with:
          repository: kit-iai-proof/proof-ci-scripts
          path: ci-scripts
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven
          server-id: 'github-proof'
          server-password: GITHUB_TOKEN

      - name: Setup path for scripts
        run: echo "$GITHUB_WORKSPACE/ci-scripts" >> "$GITHUB_PATH"

      - name: Verify version
        run: ./ci-scripts/check-mvn-git-project-version-match

      - name: Deploy mvn artifact
        run: mvn clean compile deploy
